conda_environment: "workflow/envs/nextstrain.yaml"

genesforglycosylation: ["G", "F"]

buildstorun: ["genome"]

description: "config/description.md"

subtypes: ['b', 'a']

filter:
  group_by: "year country"
  min_length:
    genome: 10000
    G: 600
    F: 600
  subsample_max_sequences: 10000 

files:
  color_schemes: "config/colors.tsv"
  auspice_config: "config/auspice_config.json"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  divergence_unit: "mutations"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "country"